version: '3.8'
services:
  db:
    image: postgres:15.3
    container_name: crisis-link-postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    env_file:
      - .env
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'psql -h $DATABASE_HOST -U $DATABASE_USER -c select 1 -d $DATABASE_NAME',
        ]
      interval: 10s
      timeout: 20s
      retries: 120
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crisis-link-api
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
